### ISSUE TITLE
Call logs show first call First

### ISSUE THREAD

**Issue by VITHANINILKANTH** [wickerlabs/CallLogs#3]
Dear sir
I use your library and complete app but first call show first genaraly last call show first 
so please help me

**Comment by Sattdr** [comment]
Nice..

**Comment by wickerlabs** [comment]
As you can see from the screenshot of the sample app, the call logs are listed in such a way that the most recent one is at the top. Do check your implementation. If it continues, provide a code snippet for the part where you populate your list and call the library.

**Comment by Sattdr** [comment]
Bye
